#!/usr/bin/env python3
"""Render the brand pack's PNG assets from the SVG masters, using Chromium so the
real Clash Display / Satoshi faces are used for the wordmark rather than a fallback.

Every PNG in logo/png/ is generated by this script. Re-run it after changing any SVG.
"""
import base64, pathlib
from playwright.sync_api import sync_playwright

PACK = pathlib.Path(__file__).resolve().parent.parent
SVG, PNG, TYPE = PACK / 'logo/svg', PACK / 'logo/png', PACK / 'type'
PNG.mkdir(parents=True, exist_ok=True)

GROUND, YELLOW, CYAN, INK = '#08090b', '#ffdd33', '#3fe3ff', '#f5f6f8'

def font_face(name, file, weight):
    b64 = base64.b64encode((TYPE / file).read_bytes()).decode()
    return (f"@font-face{{font-family:'{name}';font-weight:{weight};font-display:block;"
            f"src:url(data:font/woff2;base64,{b64}) format('woff2');}}")

FONTS = (font_face('Clash Display', 'clash-display-600.woff2', 600)
         + font_face('Clash Display', 'clash-display-700.woff2', 700)
         + font_face('Satoshi', 'satoshi-500.woff2', 500))

def page_html(body, css='', w=1024, h=1024):
    return f"""<!doctype html><meta charset="utf-8"><style>
    {FONTS}
    *{{margin:0;padding:0;box-sizing:border-box}}
    html,body{{width:{w}px;height:{h}px;background:transparent;
      display:flex;align-items:center;justify-content:center;overflow:hidden}}
    {css}</style>{body}"""

def mark_svg(name):
    return (SVG / name).read_text()

# ── the assets to produce ────────────────────────────────────────────────────
# (filename, width, height, html-body, extra-css, transparent?)
def build():
    out = []
    g = mark_svg('mark-gradient.svg')
    yc = mark_svg('mark-yellowcyan.svg')
    mw = mark_svg('mark-mono-white.svg')

    def sized(svg, px):
        # the mark's viewBox is 72x82 — scale to fit the box on its long side
        return svg.replace('width="288" height="328"',
                           f'width="{round(px*72/82)}" height="{px}"')

    # square icons, transparent, mark alone
    for px in (1024, 512, 256, 180, 64, 32):
        out.append((f'mark-gradient-{px}.png', px, px, sized(g, int(px*0.86)), '', True))

    # app/avatar tiles — mark on the charcoal ground, rounded
    for px in (1024, 512):
        out.append((f'avatar-charcoal-{px}.png', px, px, sized(g, int(px*0.62)),
                    f'html,body{{background:{GROUND};border-radius:{px*0.22}px}}', False))

    out.append(('apple-touch-icon-180.png', 180, 180, sized(g, 112),
                f'html,body{{background:{GROUND}}}', False))
    out.append(('favicon-32.png', 32, 32, sized(g, 30), '', True))

    # mono versions, transparent
    out.append(('mark-mono-white-1024.png', 1024, 1024, sized(mw, 880), '', True))
    out.append(('mark-yellowcyan-1024.png', 1024, 1024, sized(yc, 880), '', True))

    # horizontal lockup: mark + wordmark, real Clash Display
    lock = (f'<div class="lk">{sized(g, 96)}'
            f'<span class="wm">Stacked<em>Out</em></span></div>')
    lock_css = ("""
      .lk{display:flex;align-items:center;gap:26px}
      .wm{font-family:'Clash Display';font-weight:700;font-size:78px;letter-spacing:-.02em;
          line-height:1;white-space:nowrap}
      .wm em{font-style:normal}""")
    out.append(('lockup-horizontal-dark.png', 720, 200, lock,
                lock_css + f'html,body{{background:transparent}}.wm{{color:{INK}}}'
                f'.wm em{{color:{YELLOW}}}', True))
    out.append(('lockup-horizontal-light.png', 720, 200, lock,
                lock_css + f'html,body{{background:transparent}}.wm{{color:{GROUND}}}'
                f'.wm em{{color:#b38a00}}', True))
    out.append(('lockup-on-charcoal.png', 900, 300, lock,
                lock_css + f'html,body{{background:{GROUND}}}.wm{{color:{INK}}}'
                f'.wm em{{color:{YELLOW}}}', False))
    return out

def main():
    jobs = build()
    with sync_playwright() as p:
        b = p.chromium.launch()
        for name, w, h, body, css, transparent in jobs:
            pg = b.new_page(viewport={'width': w, 'height': h},
                            device_scale_factor=1)
            pg.set_content(page_html(body, css, w, h))
            pg.wait_for_timeout(220)          # let the embedded faces settle
            pg.screenshot(path=str(PNG / name), omit_background=transparent)
            pg.close()
            print(f'  {name}  {w}x{h}')
        b.close()
    print(f'\n{len(jobs)} PNGs written to {PNG}')

if __name__ == '__main__':
    main()
